# Generated by Django 5.1.4 on 2024-12-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download_url',
            field=models.URLField(help_text='Direct download link for the movie', null=True),
        ),
    ]
