# Generated by Django 5.1.4 on 2024-12-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_comment_text_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='youtube_trailer_id',
            field=models.CharField(blank=True, help_text='YouTube video ID from the URL', max_length=20),
        ),
    ]
